# .scrutinizer.yml
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true

tools:
    external_code_coverage:
        enabled: false

    php_cpd:
        enabled: true

    php_cs_fixer:
        enabled: true
        config:
            level: psr2

    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant:  false

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    php_code_coverage:
        enabled: false

    php_code_sniffer:
        config:
            standard: PSR2

    sensiolabs_security_checker:
        enabled: true

filter:
    dependency_paths:
        - Contrib/
