categories:
  BootstrapPackage:
    label: 'Bootstrap Package'
  BootstrapPackage.logo:
    label: 'Logo'
    parent: BootstrapPackage
  BootstrapPackage.favicon:
    label: 'Favicon'
    parent: BootstrapPackage
  BootstrapPackage.templates:
    label: 'Templates'
    parent: BootstrapPackage
  BootstrapPackage.templates.page:
    label: 'Pages'
    parent: BootstrapPackage.templates
  BootstrapPackage.templates.block:
    label: 'Block'
    parent: BootstrapPackage.templates
  BootstrapPackage.templates.plugin:
    label: 'Plugin'
    parent: BootstrapPackage.templates
  BootstrapPackage.navigation:
    label: 'Navigation'
    parent: BootstrapPackage
  BootstrapPackage.navigation.main:
    label: 'Main'
    parent: BootstrapPackage.navigation
  BootstrapPackage.navigation.dropdown:
    label: 'Dropdown'
    parent: BootstrapPackage.navigation
  BootstrapPackage.navigation.sub:
    label: 'Subnavigation'
    parent: BootstrapPackage.navigation
  BootstrapPackage.navigation.breadcrumb:
    label: 'Breadcrumb'
    parent: BootstrapPackage.navigation
  BootstrapPackage.navigation.meta:
    label: 'Meta'
    parent: BootstrapPackage.navigation
  BootstrapPackage.navigation.footer:
    label: 'Footer'
    parent: BootstrapPackage.navigation
  BootstrapPackage.navigation.language:
    label: 'Language'
    parent: BootstrapPackage.navigation
  BootstrapPackage.contact:
    label: 'Contact'
    parent: BootstrapPackage
  BootstrapPackage.contact.data:
    label: 'Data'
    parent: BootstrapPackage.contact
  BootstrapPackage.contact.button:
    label: 'Button'
    parent: BootstrapPackage.contact
  BootstrapPackage.copyright:
    label: 'Copyright'
    parent: BootstrapPackage
  BootstrapPackage.socialmedia:
    label: 'Social Media'
    parent: BootstrapPackage
  BootstrapPackage.meta:
    label: 'Meta'
    parent: BootstrapPackage
  BootstrapPackage.config:
    label: 'Config'
    parent: BootstrapPackage
  BootstrapPackage.settings:
    label: 'Settings'
    parent: BootstrapPackage

