#!/usr/bin/env bash
#ddev-generated
## What has to be true in the web container before a worktree can be served,
## and what makes one reachable afterwards.
##
## DDEV sources every file in .ddev/web-entrypoint.d into its own start script,
## under errexit and before the web server is up; the application runs this same
## file as a command, through sudo, whenever a worktree changes something. Which
## of the two it is is the first thing decided below.
##
## What is written -- the server blocks, and which worktrees ask for a PHP of
## their own -- is decided by functions that take what they need and print what
## they make. That half needs no container, no root and no project, and it is
## the most fragile thing this add-on ships: sed on pool configurations, pgrep
## and pkill on php-fpm masters, server blocks for two web servers. See
## tests/scripts.bats. Applying it is what happens below the line.

# Sourced, this hands itself back as a process of its own: nothing below is then
# defined in DDEV's shell, neither its arguments nor its errexit are this file's
# to inherit, and the trace it runs under stays out of the container's log.
if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
    bash "${BASH_SOURCE[0]}" start \
        || echo "[branchery] The entry point failed; the worktrees may not be served. See above."
    return 0
fi

set -euo pipefail

STATE="/var/www/html/.ddev/branchery/var"
MAP="${STATE}/php.map"
DOCROOTS="${STATE}/docroots"

# The addresses hang under the project's own name.
tld="${DDEV_SITENAME:-ddev}.${DDEV_TLD:-ddev.site}"
escaped_tld="$(printf '%s' "$tld" | sed 's/\./\\./g')"

log() { printf '[branchery] %s\n' "$*"; }

# Which web server actually serves this project -- not "which configuration
# directory is there": DDEV's web image carries nginx and Apache both, so that
# question always answers nginx and an Apache project would be handed a
# configuration nothing reads. DDEV names the one in charge in the environment.
webserver() {
    case "${DDEV_WEBSERVER_TYPE:-}" in
        nginx*) echo nginx ;;
        apache*) echo apache ;;
        *)
            if pgrep -x apache2 >/dev/null 2>&1; then
                echo apache
            elif pgrep -x nginx >/dev/null 2>&1; then
                echo nginx
            fi
            ;;
    esac
}

# The addresses of the worktrees: <worktree>.<project>.<tld> -> a link under
# var/docroots. One link per worktree pointing at its web directory, so every
# project can have a docroot of its own and a new worktree is reachable right
# away, without reloading the web server.

nginx_config() {
    cat <<EOF
# Generated by the worktree management -- do not edit by hand.
server {
    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    # The first part of the hostname names the worktree.
    server_name ~^(?<worktree>[a-z0-9-]+)\\.${escaped_tld}\$;
    root ${DOCROOTS}/\$worktree;

    include /etc/nginx/monitoring.conf;
    index index.php index.html;
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    location / {
        absolute_redirect off;
        try_files \$uri \$uri/ /index.php\$is_args\$args;
    }

    location ~ \\.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\\.php)(/.+)\$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_read_timeout 10m;
        fastcgi_param SERVER_NAME \$host;
        fastcgi_param HTTPS \$fcgi_https;
    }

    include /mnt/ddev_config/nginx/*.conf;
}
EOF
}

apache_config() {
    local block
    block() {
        local port="$1" ssl="$2"
        cat <<EOF
<VirtualHost *:${port}>
    ServerName worktrees.${tld}
    ServerAlias *.${tld}
${ssl}
    UseCanonicalName Off
    VirtualDocumentRoot ${DOCROOTS}/%1

    RewriteEngine On
    RewriteCond %{HTTP:X-Forwarded-Proto} =https
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
    RewriteRule ^(.+[^/])\$ https://%{HTTP_HOST}\$1/ [redirect,last]

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on

    <Directory "${DOCROOTS}">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    <Directory "/var/www/html/.worktrees">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog \${APACHE_LOG_DIR}/access.log combined

    # The TYPO3 backend sets large cookies.
    LimitRequestFieldSize 16380
    Alias "/phpstatus" "/var/www/phpstatus.php"
</VirtualHost>
EOF
    }

    printf '# Generated by the worktree management -- do not edit by hand.\n\n'
    block 80 ''
    block 443 '
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/master.crt
    SSLCertificateKeyFile /etc/ssl/certs/master.key
'
}

# The PHP version of each worktree. The source is var/php.map
# ("<worktree>=<version>"). For every version that deviates from the project
# default, an additional PHP-FPM pool runs on its own socket; the web server
# gets an entry for that worktree which points the handler there.

# Which worktrees ask for a PHP of their own, out of the map: one
# "<worktree> <version>" to a line, in the map's order. Every rule about what
# counts is here and nothing else is.
wanted() {
    local map="$1" docroots="$2" default="$3"
    [ -f "$map" ] || return 0

    local worktree version
    while IFS='=' read -r worktree version; do
        worktree="$(printf '%s' "${worktree:-}" | tr -d '[:space:]')"
        version="$(printf '%s' "${version:-}" | tr -d '[:space:]')"
        [ -n "$worktree" ] && [ -n "$version" ] || continue
        case "$worktree" in \#*) continue ;; esac
        # A worktree the map has outlived: its line says nothing about anything.
        # Asked of the link and not of what it points at: a docroot the build has
        # not made yet -- "public" before composer ran -- is a link that leads
        # nowhere, and the version is chosen a step before that. Skipped here, the
        # worktree is served by the project's PHP until something applies this again.
        [ -e "${docroots}/${worktree}" ] || [ -L "${docroots}/${worktree}" ] || continue
        # The project's own version is what the wildcard already serves.
        [ "$version" = "$default" ] && continue
        printf '%s %s\n' "$worktree" "$version"
    done < "$map"
}

nginx_block() {
    local worktree="$1" version="$2"
    cat <<EOF
# ${worktree} runs with PHP ${version}
server {
    listen 80;
    listen 443 ssl;
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    server_name ${worktree}.${tld};
    root ${DOCROOTS}/${worktree};

    include /etc/nginx/monitoring.conf;
    index index.php index.html;
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    location / {
        absolute_redirect off;
        try_files \$uri \$uri/ /index.php\$is_args\$args;
    }

    location ~ \\.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\\.php)(/.+)\$;
        fastcgi_pass unix:/run/php/php-fpm-${version}.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_read_timeout 10m;
        fastcgi_param SERVER_NAME \$host;
        fastcgi_param HTTPS \$fcgi_https;
    }

    include /mnt/ddev_config/nginx/*.conf;
}
EOF
}

apache_block() {
    local worktree="$1" version="$2"
    # Cover both views: the web server evaluates <Directory> against the path
    # the docroot is reached through, while the files live in the worktree.
    for path in "${DOCROOTS}/${worktree}" "/var/www/html/.worktrees/${worktree}"; do
        cat <<EOF
<Directory "${path}">
    <FilesMatch "\\.ph(ar|p|tml)\$">
        SetHandler "proxy:unix:/run/php/php-fpm-${version}.sock|fcgi://localhost"
    </FilesMatch>
</Directory>
EOF
    done
}

# Read rather than run: a test sources this for the functions above and applies
# nothing. Everything below this line touches the container.
[ "${BRANCHERY_SCRIPT_READ_ONLY:-}" = "1" ] && return 0

# DDEV sources this as the project's user, while the application runs it through
# sudo. The pools, the server configuration and the path the link below stands
# on are root's to write, so both ends go through here and the outcome does not
# depend on which one asked.
as_root() {
    if [ "$(id -u)" = 0 ]; then "$@"; else sudo -n "$@"; fi
}

vhosts() {
    mkdir -p "$DOCROOTS"

    case "$(webserver)" in
        nginx)
            # The other server's copy goes: a project that switched over would
            # otherwise keep being served by a configuration nobody writes any more.
            rm -f /etc/apache2/sites-enabled/zz-branchery.conf
            nginx_config > /etc/nginx/sites-enabled/zz-branchery.conf
            if pgrep -x nginx >/dev/null 2>&1 && nginx -t >/dev/null 2>&1; then
                nginx -s reload
            fi
            ;;
        apache)
            rm -f /etc/nginx/sites-enabled/zz-branchery.conf
            # VirtualDocumentRoot maps an address to a worktree and comes from a
            # module Apache does not enable by itself. Enabled here rather than
            # through a Dockerfile in the project: DDEV runs this before the
            # server starts, so the module is up by the time anything reads the
            # configuration below, and the repository carries one file fewer.
            a2enmod vhost_alias >/dev/null 2>&1 \
                || log "Could not enable mod_vhost_alias; the worktree addresses will not resolve."
            apache_config > /etc/apache2/sites-enabled/zz-branchery.conf
            if pgrep -x apache2 >/dev/null 2>&1 && apachectl -t >/dev/null 2>&1; then
                apachectl graceful 2>&1 | grep -vF "Could not reliably determine" || true
            fi
            ;;
    esac
}

# Called again for a pool that is already up, this changes nothing: the entry
# point runs on every container start, and every worktree asks for its version.
#
# Says so when nothing listens afterwards. It used to say the opposite -- the
# exit code of php-fpm went into a pipe -- so a pool that never bound its socket
# still got a server block, and every request to that worktree was a 502.
start_fpm() {
    local version="$1"
    local socket="/run/php/php-fpm-${version}.sock"
    local pool="/etc/php/${version}/fpm/pool.d/www.conf"
    local master="/etc/php/${version}/fpm/php-fpm.conf"

    [ -x "/usr/sbin/php-fpm${version}" ] || { log "PHP ${version} has no php-fpm in this image."; return 1; }
    [ -f "$pool" ] || { log "No pool configuration for PHP ${version}."; return 1; }

    # A socket of its own, in the one directory under /run that belongs to the
    # project's user: a socket straight under root's /run is one the entry point
    # cannot bind. Plus an explicit user, so the pool can also be started as root.
    sed -i \
        -e "s|^listen = .*|listen = ${socket}|" \
        -e "s|^;\?user = .*|user = ${WEB_USER}|" \
        -e "s|^;\?group = .*|group = ${WEB_GROUP}|" \
        "$pool"
    grep -q '^user = ' "$pool" || printf 'user = %s\ngroup = %s\n' "$WEB_USER" "$WEB_GROUP" >> "$pool"

    if pgrep -f "$master" >/dev/null 2>&1; then
        [ -S "$socket" ] && return 0
        # Up, but on the socket an earlier version of this script put it on.
        # Nothing reaches it there, so it goes and comes back where the server
        # blocks below point.
        log "PHP ${version} FPM runs without ${socket}; starting it again."
        pkill -f "$master" || true
        for _ in 1 2 3 4 5 6 7 8 9 10; do
            pgrep -f "$master" >/dev/null 2>&1 || break
            sleep 0.5
        done
    fi

    rm -f "$socket"
    if ! "/usr/sbin/php-fpm${version}" -D; then
        log "PHP ${version} FPM did not start."
        return 1
    fi
    # -D returns once the master is up; the socket follows within a moment.
    for _ in 1 2 3 4 5 6 7 8 9 10; do
        [ -S "$socket" ] && break
        sleep 0.2
    done
    if [ ! -S "$socket" ]; then
        log "PHP ${version} FPM started but did not bind ${socket}."
        return 1
    fi
    log "PHP ${version} FPM started (${socket})."
}

php_versions() {
    local target server started failed worktree version

    DEFAULT_PHP="$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')"
    WEB_USER="$(stat -c %U /var/www/html)"
    WEB_GROUP="$(stat -c %G /var/www/html)"

    server="$(webserver)"
    case "$server" in
        nginx)
            target="/etc/nginx/sites-enabled/zy-branchery-php.conf"
            rm -f /etc/apache2/sites-enabled/zz-branchery-php.conf
            ;;
        apache)
            target="/etc/apache2/sites-enabled/zz-branchery-php.conf"
            rm -f /etc/nginx/sites-enabled/zy-branchery-php.conf
            ;;
        *) return 0 ;;
    esac

    : > "${target}.tmp"
    started=""
    failed=""

    while read -r worktree version; do
        # A worktree whose pool is not up gets no entry: without one it is caught
        # by the wildcard and served with the project's PHP, which answers.
        case " $started " in
            *" $version "*) ;;
            *)
                case " $failed " in
                    *" $version "*)
                        log "No entry for ${worktree}: PHP ${version} is not up."
                        continue
                        ;;
                esac
                if start_fpm "$version"; then
                    started="${started} ${version}"
                else
                    failed="${failed} ${version}"
                    log "No entry for ${worktree}: PHP ${version} is not up, the project's PHP serves it until it is."
                    continue
                fi
                ;;
        esac

        if [ "$server" = nginx ]; then
            nginx_block "$worktree" "$version" >> "${target}.tmp"
        else
            apache_block "$worktree" "$version" >> "${target}.tmp"
        fi
    done < <(wanted "$MAP" "$DOCROOTS" "$DEFAULT_PHP")

    mv "${target}.tmp" "$target"

    if [ "$server" = nginx ]; then
        if pgrep -x nginx >/dev/null 2>&1 && nginx -t >/dev/null 2>&1; then
            nginx -s reload
            log "nginx reloaded."
        fi
    elif pgrep -x apache2 >/dev/null 2>&1; then
        if apachectl -t >/dev/null 2>&1; then
            apachectl graceful 2>&1 | grep -vF "Could not reliably determine" || true
            log "Apache reloaded."
        fi
    fi
}

# Git worktrees store absolute host paths; a symlink makes both views line up
# so that git works inside the container as well.
#
# Not fatal either way: the directory above the project is root's for every
# project outside /home, and a link that could not be made costs git inside the
# container its worktrees, not the developer their project. A Windows drive is
# nothing a link can stand for and is left alone.
host_path() {
    if [ -n "${HOST_PROJECT_ROOT:-}" ] && [ "${HOST_PROJECT_ROOT}" != "/var/www/html" ]; then
        case "${HOST_PROJECT_ROOT}" in
            /*)
                if ! as_root mkdir -p "$(dirname "${HOST_PROJECT_ROOT}")" \
                    || ! as_root ln -sfn /var/www/html "${HOST_PROJECT_ROOT}"; then
                    log "Could not link ${HOST_PROJECT_ROOT} to /var/www/html; git will not find the worktrees by their host path inside the container."
                fi
                ;;
            *)
                log "${HOST_PROJECT_ROOT} is not an absolute POSIX path; the project is not linked under it."
                ;;
        esac
    fi

    git config --global --add safe.directory '*' 2>/dev/null || true
}

start() {
    # The addresses and the PHP pools of the worktrees, as they stand right now.
    # Neither may stop the container from coming up: a project whose worktrees
    # cannot be configured is still a project its developer needs running.
    as_root bash "$0" vhosts || log "The worktree addresses were not applied. See above."
    as_root bash "$0" php-versions || log "The PHP versions of the worktrees were not applied. See above."
    host_path
}

# The container start asks for all of it; the application asks for the part a
# worktree just changed.
case "${1:-start}" in
    start) start ;;
    vhosts) vhosts ;;
    php-versions) php_versions ;;
    *) log "Unknown command: ${1}" >&2; exit 64 ;;
esac
